#!/usr/bin/env php
<?php
require_once('vendor/autoload.php');

$image_block_size = 10;
$css_block_size = 10;


$image_filename = $argv[1];
$canvas = new \Entities\CssCanvas($image_filename, $css_block_size);
$writer = new \Helpers\ArtWriterHelper($canvas);

$image = new \Entities\Image($image_filename);

list($width, $height) = [$image->get_width(), $image->get_height()];

for($x = 0; $x < $width / $image_block_size; $x ++)
{
	for($y = 0; $y < $height / $image_block_size; $y ++)
	{
		$rgb = $image->get_rgb_at($x * $image_block_size, $y * $image_block_size);
		$pixel = new \Entities\Pixel($rgb, $x, $y);

		$canvas->add_box_shadow($pixel);
	}
}

$writer->write_html_file();
