#!/usr/bin/env php
<?php
require_once('vendor/autoload.php');

$image_block_size = 10;
$css_block_size = 10;
$image_filename = $argv[1];

$css_pixel_art = new \CssPixelArt\CssPixelArt($image_block_size, $css_block_size, $image_filename);
$css_pixel_art->write_html_file('dist/' . basename($image_filename) . '.html');
//$css_pixel_art->output_css();
